---
- name: USER | Create {{ user }} user
  user:
    name: "{{ user }}"
    shell: /bin/bash

- name: USER | Add SSH key access
  authorized_key:
      user: "{{ user }}"
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
